# Generated by Django 3.1.3 on 2020-11-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
