# Generated by Django 3.1.3 on 2020-11-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_api', '0007_auto_20201130_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.TextField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nif',
            field=models.IntegerField(unique=True, verbose_name='Tax identification code'),
        ),
    ]
