# Generated by Django 3.1.3 on 2020-11-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_api', '0008_auto_20201130_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
