# Generated by Django 3.1.3 on 2020-11-30 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_api', '0009_auto_20201130_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_modified_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last modified at'),
        ),
    ]
