# Generated by Django 3.1.3 on 2020-11-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_api', '0010_auto_20201130_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
