# Generated by Django 3.1.3 on 2020-11-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_api', '0014_auto_20201130_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='other',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total rooms'),
        ),
    ]
